# Generated by Django 5.2.9 on 2025-12-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_userpreferences_card_text_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='card_text_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('xlarge', 'Extra Large'), ('xxlarge', '2X Large'), ('xxxlarge', '3X Large')], default='large', max_length=10),
        ),
    ]
