# Generated by Django 5.2.9 on 2025-12-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_add_email_preferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('started', 'Started'), ('success', 'Success'), ('failure', 'Failure')], max_length=20)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('users_processed', models.IntegerField(default=0)),
                ('emails_sent', models.IntegerField(default=0)),
                ('errors_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['command_name', 'started_at'], name='cards_comma_command_300003_idx')],
            },
        ),
    ]
