# Generated by Django 5.2.9 on 2025-12-07 19:34

from django.db import migrations, models


def set_has_been_reviewed(apps, schema_editor):
    """Set has_been_reviewed=True for cards that have review logs."""
    Card = apps.get_model('cards', 'Card')
    ReviewLog = apps.get_model('cards', 'ReviewLog')

    # Get IDs of all cards that have been reviewed
    reviewed_card_ids = ReviewLog.objects.values_list('card_id', flat=True).distinct()

    # Update those cards
    Card.objects.filter(id__in=reviewed_card_ids).update(has_been_reviewed=True)


def reverse_migration(apps, schema_editor):
    """Reverse: set all has_been_reviewed to False."""
    Card = apps.get_model('cards', 'Card')
    Card.objects.all().update(has_been_reviewed=False)


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_commandexecutionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='has_been_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(set_has_been_reviewed, reverse_migration),
    ]
