# Generated by Django 5.2.9 on 2025-12-08 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_add_has_been_reviewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('basic', 'Basic (Front/Back)'), ('cloze', 'Cloze Deletion'), ('reverse', 'Basic + Reverse'), ('typein', 'Type-In Answer')], default='basic', max_length=20),
        ),
    ]
