# Generated by Django 5.2.9 on 2025-12-08 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_add_typein_card_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='celebration_animations',
            field=models.BooleanField(default=True),
        ),
    ]
