# Generated by Django 5.2.9 on 2025-12-08 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_add_celebration_animations'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='user_timezone',
            field=models.CharField(choices=[('UTC', 'UTC'), ('US/Eastern', 'US Eastern'), ('US/Central', 'US Central'), ('US/Mountain', 'US Mountain'), ('US/Pacific', 'US Pacific'), ('US/Alaska', 'US Alaska'), ('US/Hawaii', 'US Hawaii'), ('Europe/London', 'Europe/London'), ('Europe/Paris', 'Europe/Paris'), ('Europe/Berlin', 'Europe/Berlin'), ('Europe/Moscow', 'Europe/Moscow'), ('Asia/Tokyo', 'Asia/Tokyo'), ('Asia/Shanghai', 'Asia/Shanghai'), ('Asia/Singapore', 'Asia/Singapore'), ('Asia/Kolkata', 'Asia/Kolkata'), ('Asia/Dubai', 'Asia/Dubai'), ('Australia/Sydney', 'Australia/Sydney'), ('Australia/Melbourne', 'Australia/Melbourne'), ('Pacific/Auckland', 'Pacific/Auckland'), ('America/Toronto', 'America/Toronto'), ('America/Vancouver', 'America/Vancouver'), ('America/Sao_Paulo', 'America/Sao Paulo'), ('America/Mexico_City', 'America/Mexico City')], default='UTC', help_text='Your local timezone for accurate daily statistics', max_length=50),
        ),
    ]
