# Generated by Django 5.2.9 on 2025-12-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_userpreferences_user_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreferences',
            name='cards_per_session',
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='max_reviews_per_session',
            field=models.IntegerField(default=0, help_text='Maximum review cards per session (0 = unlimited)'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='new_cards_per_day',
            field=models.IntegerField(default=20, help_text='Maximum number of new cards to introduce per session'),
        ),
    ]
